#FROM cnstark/pytorch:2.0.1-py3.10.11-cuda11.8.0-ubuntu22.04
From pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel
ARG PYTHON_VERSION=3.10
ARG USER_NAME=brody9512
# ###########################
ENV USER_NAME=${USER_NAME}
MAINTAINER ${USER_NAME}

#####If not build your image remove this '#' in ENV #####
#ENV http_proxy http://192.168.45.108:3128
#ENV https_proxy http://192.168.45.108:3128

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


# RUN addgroup --gid 1000001 gusers
# RUN adduser --uid 1000160 --gid 1000001 --disabled-password --gecos '' $USER_NAME

# RUN adduser $USER_NAME sudo

#RUN apt-get update && apt-get upgrade -y
ENV HTTP_PROXY=http://192.168.45.108:3128
ENV HTTPS_PROXY=http://192.168.45.108:3128

RUN apt-get update -y --allow-unauthenticated
RUN apt-get upgrade -y

RUN apt-get install -y apt-utils vim libgl1-mesa-glx python3-pip
# to skip build error for timezone
RUN apt-get update
RUN apt-get install -y sudo vim python3-pip
# Solve python module opency-python dependency
RUN apt-get install -y libgl1-mesa-glx
# Solve python module openslide-python dependency
RUN apt-get install -y openslide-tools
RUN apt-get install -y libgtk2.0-dev
RUN apt-get install -y libsm6
RUN apt-get install -y libxext6
RUN apt-get install -y libxrender-dev
RUN apt-get install -y python-tk
RUN apt-get install -y libglib2.0-0
RUN apt-get install -y libsm6
RUN apt-get install -y libxrender1
RUN apt-get install -y libfontconfig1
RUN apt-get install -y dcm2niix

# to skip build error for timezone
#ENV TZ=Asia/Seoul
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Solve python module opency-python dependency
# libgl1-mesa-glx is already installed above
# Solve python module openslide-python dependency

#### past ###
# USER ${USER_NAME}
# RUN mkdir -p /home/$USER_NAME/workspace
# RUN mkdir -p /home/$USER_NAME/.local
# RUN mkdir -p /home/$USER_NAME/.local/bin
# WORKDIR /home/$USER_NAME

RUN mkdir -p /workspace
RUN mkdir -p /.local
RUN mkdir -p /.local/bin
WORKDIR /

# RUN pip install numpy SimpleITK jupyter jupyterlab keras pandas matplotlib seaborn opencv-python pydicom natsort albumentations tensorboardX xlrd pylibjpeg pylibjpeg-libjpeg tqdm scikit-image scikit-learn

RUN pip install numpy==1.26.0 pandas==2.1.1 natsort==8.4.0 matplotlib==3.8.0 tqdm scikit-image scikit-learn==1.3.2 \
kornia==0.7.0 opencv-python==4.8.0.76 monai==1.3.0 torchvision==0.14.1 livelossplot==0.5.5 imutils grad-cam pytorch-gradcam \
seaborn ipywidgets albumentations==1.4.3 pydicom segmentation-models-pytorch==0.3.3 pylibjpeg-openjpeg openpyxl gpustat \
scikit-posthocs medpy openslide-python tiatoolbox torchmetrics==1.2.0 neurokit2==0.2.7 librosa==0.10.1 scipy==1.11.2 \
wandb==0.16.0 libauc==1.3.0 pytorch-lightning==2.1.2 pillow pylibjpeg pylibjpeg-libjpeg pydicom[gdcm] 

